#include "F28x_Project.h"
#include "KEY_LED.h"

// 配置LED
void InitLED(void)
{
    GPIO_SetupPinMux(LED1_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(LED1_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);

    GPIO_SetupPinMux(LED2_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(LED2_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);

    GPIO_SetupPinMux(VAVLE_CLOSE_LED_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(VAVLE_CLOSE_LED_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);

    GPIO_SetupPinMux(VAVLE_OPEN_LED_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(VAVLE_OPEN_LED_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);   

    GPIO_SetupPinMux(POS_LED_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(POS_LED_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);   
    
    GPIO_SetupPinMux(PRE_LED_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(PRE_LED_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);   
    
    GPIO_SetupPinMux(RS232_LED_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(RS232_LED_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);   
    
    GPIO_SetupPinMux(BATT_LED_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(BATT_LED_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);  

    GPIO_SetupPinMux(RUN_LED_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(RUN_LED_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);   

    GPIO_SetupPinMux(FAULT_LED_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(FAULT_LED_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);   

    GPIO_SetupPinMux(VAVLE_OPEN_KEY_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(VAVLE_OPEN_KEY_PIN, GPIO_INPUT, GPIO_PULLUP);   

    GPIO_SetupPinMux(VAVLE_CLOSE_KEY_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(VAVLE_CLOSE_KEY_PIN, GPIO_INPUT, GPIO_PULLUP);   

    // 设置TTL输出引脚
    // 这些引脚用于控制阀门的开关
    GPIO_SetupPinMux(VAVLE_OPEN_TTL_OUT_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(VAVLE_OPEN_TTL_OUT_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);
    GPIO_WritePin(VAVLE_OPEN_TTL_OUT_PIN, 1); // 默认关闭


    GPIO_SetupPinMux(VAVLE_CLOSE_TTL_OUT_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(VAVLE_CLOSE_TTL_OUT_PIN, GPIO_OUTPUT, GPIO_PUSHPULL);  
    GPIO_WritePin(VAVLE_CLOSE_TTL_OUT_PIN, 1); // 默认关闭

    // 设置TTL输入引脚
    // 这些引脚用于控制阀门状态 
    GPIO_SetupPinMux(VAVLE_OPEN_TTL_IN_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(VAVLE_OPEN_TTL_IN_PIN, GPIO_INPUT, GPIO_PULLUP);   

    GPIO_SetupPinMux(VAVLE_CLOSE_TTL_IN_PIN, GPIO_MUX_CPU1, 0);
    GPIO_SetupPinOptions(VAVLE_CLOSE_TTL_IN_PIN, GPIO_INPUT, GPIO_PULLUP);   

}